config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'

  # Administrador
  get 'admin', to: 'admin#index'

  scope '/admin' do
    get 'usuarios', to: 'perfil#index', as: 'admin_usuarios'
    get 'locales', to: 'admin#ver_locales', as: 'admin_locales'
    delete 'locales/:local_id', to: 'admin#eliminar_local', as: 'admin_delete_local'
    get 'aceptar_locales', to: 'admin#aceptar_locales', as: 'admin_aceptar_locales'
    patch 'aceptar_locales/:local_id', to: 'admin#aceptar_local', as: 'admin_aceptar_local'
    resources :comunas, controller: 'communes'
    resources :gustos, controller: 'interests'
    resources :comentarios, controller: 'comments', only: %i[index destroy]
  end

  # Locales, Menus y Comentarios
  resources :locales, controller: 'locals', as: 'local' do
    resources :menus, only: %i[new create edit update destroy]
    resources :comentarios, controller: 'comments', only: %i[new create destroy]
    resources :valoraciones, controller: 'valuations', only: %i[edit update destroy]
  end
  # Perfil
  # Create
  devise_for :users, controllers: { sessions: 'users/sessions',
                                    registrations: 'users/registrations' }

  # Ver menus
  get 'locales/:local_id/edit/menus', to: 'menus#show', as: :local_menues

  # Imagenes del local
  get 'locales/:local_id/edit/imagenes', to: 'locals#images', as: :local_images
  patch 'locales/:local_id/edit/imagenes', to: 'locals#update_images', as: :local_add_images
  delete 'locales/:local_id/edit/imagenes/:image_id', to: 'locals#delete_images',
                                                      as: :local_delete_images

  # Ver comentarios
  get 'perfil/:user_id/comentarios', to: 'comments#show', as: :perfil_comentarios
  # Ver valoraciones pendientes
  get 'perfil/:user_id/valoraciones', to: 'perfil#valuations', as: :perfil_valuations

  # Read perfil
  get 'perfil/:user_id', to: 'perfil#show', as: :perfil

  # Update perfil
  get 'perfil/:id/edit', to: 'perfil#edit', as: :perfil_edit
  patch 'perfil/:id', to: 'perfil#update'
  put 'perfil/:id', to: 'perfil#update'

  # Update interes
  patch 'perfil_interest/:id', to: 'perfil#update_interest', as: :perfil_edit_interest
  get 'perfil/:id/:idinterest', to: 'perfil#delete_interest', as: :perfil_delete_interest

  # Update Profile Avatar
  patch 'perfil_avatar/:user_id', to: 'perfil#update_avatar', as: :perfil_update_avatar
  delete 'perfil_avatar/:user_id', to: 'perfil#delete_avatar', as: :perfil_delete_avatar

  # Delete perfil
  delete 'perfil/:id', to: 'perfil#destroy'

  # Match
  # Mostrar perfiles
  get 'match/:id', to: 'matches#index', as: :match
  # Mostrar informacion de los matches del usuario
  get 'match/:id/info', to: 'matches#show', as: :match_info

  # Create match
  get 'match/:id/:idsolicitado', to: 'matches#new', as: :match_new
  # Aceptar/Rechazar match_request
  patch 'perfil/:id/:id_matchrequest', to: 'matches#accept_match', as: :perfil_accept_match

  # CITAS
  # Proponer Cita
  get 'appointment/:id', to: 'appointment#new', as: :new_appointment

  # Crear Cita
  post 'appointment/:id', to: 'appointment#create', as: :create_appointment

  # Aceptar Cita
  put 'perfil/:id/:appointment_id', to: 'appointment#accept', as: :accept_appointment
end

app/models/application_record.rb
# Descripcion que dice que hace la funcion
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  validates :local_id, :fecha, presence: true

  belongs_to :match
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :contenido, presence: true
  belongs_to :local
  belongs_to :user
end

app/models/comments.rb
class Comment < ApplicationRecord
end

app/models/commune.rb
class Commune < ApplicationRecord
  has_many :users, dependent: :nullify
  has_many :locals, dependent: :nullify
end

app/models/interest.rb
class Interest < ApplicationRecord
  has_and_belongs_to_many :users
end

app/models/local.rb
class Local < ApplicationRecord
  validates :nombre, :descripcion, presence: true

  has_many_attached :images

  def carousel_photo(input)
    if images[input].variable?
      images[input].variant(resize: '800x480!').processed
    else
      images[input]
    end
  rescue StandardError
    'https://bulma.io/images/placeholders/800x480.png'
  end

  belongs_to :user
  belongs_to :commune
  has_many :menus, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :valuations, dependent: :destroy
end

app/models/match.rb
class Match < ApplicationRecord
  belongs_to :user1, class_name: 'User'
  belongs_to :user2, class_name: 'User'
  has_many :appointments
end

app/models/match_request.rb
class MatchRequest < ApplicationRecord
end

app/models/menu.rb
class Menu < ApplicationRecord
  validates :nombre, :descripcion, :precio, presence: true
  belongs_to :local
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :avatar

  def comment_avatar
    if avatar.variable?
      avatar.variant(resize: '128x128!').processed
    else
      avatar
    end
  rescue StandardError
    # La imagen ha sido eliminada
    'https://bulma.io/images/placeholders/128x128.png'
  end

  def match_avatar
    if avatar.variable?
      avatar.variant(resize: '480x600!').processed
    else
      avatar
    end
  rescue StandardError
    # La imagen ha sido eliminada
    'https://bulma.io/images/placeholders/480x600.png'
  end

  belongs_to :commune
  has_and_belongs_to_many :interests
  has_one :local, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :matches
  has_many :match_requests
  has_many :valuations, dependent: :nullify
end

app/models/valuation.rb
class Valuation < ApplicationRecord
  belongs_to :user
  belongs_to :local
end

app/controllers/communes_controller.rb
class CommunesController < ApplicationController

  layout "admin"

  # Create
  def new
    @comuna = Commune.new
  end

  def create
    commune_params = params.require(:commune).permit(:nombre)
    @comuna = Commune.create(commune_params)

    if @comuna.save
      redirect_to comunas_path, notice: 'Comuna creada con éxito'
    else
      redirect_to new_comuna_path, notice: 'Ocurrió un error al crear la commune'
    end
  end

  # Read

  def index
    @comunas = Commune.all
  end

  def show
    @comuna = Commune.find(params[:id])
  end

  # Update

  def edit
    @comuna = Commune.find(params[:id])
  end

  def update
    commune_params = params.require(:commune).permit(:nombre)
    @comuna = Commune.find(params[:id])

    if @comuna.update(commune_params)
      redirect_to comuna_path(@comuna.id), notice: 'Comuna editada con éxito'
    else
      redirect_to comuna_path(@comuna.id), notice: 'Ocurrió un error al editar la commune'
    end
  end

  # Delete

  def destroy
    @comuna = Commune.find(params[:id])
    @comuna.destroy
    redirect_to comunas_path, notice: 'Comuna eliminada con éxito'
  end

end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/communes_helper.rb
module CommunesHelper
end

app/helpers/interests_helper.rb
module InterestsHelper
end

app/helpers/locals_helper.rb
module LocalsHelper
end

app/helpers/match_helper.rb
module MatchHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/miperfil_helper.rb
module MiperfilHelper
end

app/helpers/valuations_helper.rb
module ValuationsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/communes/edit.html.erb
<section class="section">
<div class="columns">
  <div class="column"></div>
  <div class="column is-4">
    <div class="box">
      <h1 class="title has-text-centered"> Editar comuna</h1>
      <%= form_with(model: @comuna, url: comuna_path(@comuna.id), method: :patch) do |form| %>
        <div class="field">
          Nombre:
          <%= form.text_field :nombre, class: "input"%>
        </div>

        <div class="actions">
          <%= form.submit 'Guardar', class: "button is-primary"%>
          <%= link_to "Volver", comuna_path(@comuna.id), class: "button is-link"%>
        </div>
      <% end %>
    </div>
  </div>
  <div class="column"></div>
</div>
</section>

app/views/communes/index.html.erb
<section class="section">
<div class="columns">
  <div class="column"></div>
  <div class="column is-4">
    <div class="box">
      <h1 class="title has-text-centered"> Comunas </h1>
      <table class="table is-striped is-fullwidth">
        <thead>
          <tr>
            <th> Nombre </th>
            <th> Acciones </th>
          </tr>
        </thead>

        <tbody>
          <% @comunas.each do |comuna| %>
            <tr>
              <td><%= comuna.nombre %>
              <td><%=link_to "Ver detalles", comuna_path(comuna.id), class: "button is-primary"%>
            </tr>
          <% end %>
        </tbody>
      </table>

      <div class="actions">
        <%= link_to "Crear comuna", new_comuna_path, class: "button is-primary"%>
        <%= link_to "Volver al panel", admin_path, class: "button is-link"%>
      </div>
    </div>
  </div>
  <div class="column"></div>
</div>
</section>

app/views/communes/new.html.erb
<section class="section">
<div class="columns">
	<div class="column"></div>
	<div class="column is-4">
		<div class="box">
			<h1 class="title has-text-centered"> Nueva comuna </h1>
			<%= form_with(model: @comuna, url: comunas_path(@comuna.id), method: :post) do |form| %>
		  		<div class="field">
		    		Nombre:
		    		<%= form.text_field :nombre, class: "input"%>
		  		</div>
				<div class="actions">
					<%= form.submit 'Crear comuna', class: "button is-primary"%>
					<%= link_to "Volver", comunas_path, class: "button is-link"%>
				</div>
			<% end %>
		</div>
	</div>
	<div class="column">
</section>

app/views/communes/show.html.erb
<section class="section">
  <div class="columns">
    <div class="column"></div>
    <div class="column is-4">
      <div class="box">
        <h1 class="title has-text-centered">Comuna de <%= @comuna.nombre %></h1>
        <div class="actions">
          <%= link_to "Editar", edit_comuna_path(@comuna.id), class: "button is-primary"%>
          <%= link_to "Eliminar", comuna_path(@comuna.id), method: :delete, class: "button is-danger",
          data: {confirm: "¿Estás seguro?"}%>
          <%= link_to "Volver", comunas_path, class: "button is-link"%>
        </div>
      </div>
    </div>
    <div class="column"></div>
  </div>
</section>