config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'

  # Administrador
  get 'admin', to: 'admin#index'

  scope '/admin' do
    get 'usuarios', to: 'perfil#index', as: 'admin_usuarios'
    get 'locales', to: 'admin#ver_locales', as: 'admin_locales'
    delete 'locales/:local_id', to: 'admin#eliminar_local', as: 'admin_delete_local'
    get 'aceptar_locales', to: 'admin#aceptar_locales', as: 'admin_aceptar_locales'
    patch 'aceptar_locales/:local_id', to: 'admin#aceptar_local', as: 'admin_aceptar_local'
    resources :comunas, controller: 'communes'
    resources :gustos, controller: 'interests'
    resources :comentarios, controller: 'comments', only: %i[index destroy]
  end

  # Locales, Menus y Comentarios
  resources :locales, controller: 'locals', as: 'local' do
    resources :menus, only: %i[new create edit update destroy]
    resources :comentarios, controller: 'comments', only: %i[new create destroy]
    resources :valoraciones, controller: 'valuations', only: %i[edit update destroy]
  end
  # Perfil
  # Create
  devise_for :users, controllers: { sessions: 'users/sessions',
                                    registrations: 'users/registrations' }

  # Ver menus
  get 'locales/:local_id/edit/menus', to: 'menus#show', as: :local_menues

  # Imagenes del local
  get 'locales/:local_id/edit/imagenes', to: 'locals#images', as: :local_images
  patch 'locales/:local_id/edit/imagenes', to: 'locals#update_images', as: :local_add_images
  delete 'locales/:local_id/edit/imagenes/:image_id', to: 'locals#delete_images',
                                                      as: :local_delete_images

  # Ver comentarios
  get 'perfil/:user_id/comentarios', to: 'comments#show', as: :perfil_comentarios
  # Ver valoraciones pendientes
  get 'perfil/:user_id/valoraciones', to: 'perfil#valuations', as: :perfil_valuations

  # Read perfil
  get 'perfil/:user_id', to: 'perfil#show', as: :perfil

  # Update perfil
  get 'perfil/:id/edit', to: 'perfil#edit', as: :perfil_edit
  patch 'perfil/:id', to: 'perfil#update'
  put 'perfil/:id', to: 'perfil#update'

  # Update interes
  patch 'perfil_interest/:id', to: 'perfil#update_interest', as: :perfil_edit_interest
  get 'perfil/:id/:idinterest', to: 'perfil#delete_interest', as: :perfil_delete_interest

  # Update Profile Avatar
  patch 'perfil_avatar/:user_id', to: 'perfil#update_avatar', as: :perfil_update_avatar
  delete 'perfil_avatar/:user_id', to: 'perfil#delete_avatar', as: :perfil_delete_avatar

  # Delete perfil
  delete 'perfil/:id', to: 'perfil#destroy'

  # Match
  # Mostrar perfiles
  get 'match/:id', to: 'matches#index', as: :match
  # Mostrar informacion de los matches del usuario
  get 'match/:id/info', to: 'matches#show', as: :match_info

  # Create match
  get 'match/:id/:idsolicitado', to: 'matches#new', as: :match_new
  # Aceptar/Rechazar match_request
  patch 'perfil/:id/:id_matchrequest', to: 'matches#accept_match', as: :perfil_accept_match

  # CITAS
  # Proponer Cita
  get 'appointment/:id', to: 'appointment#new', as: :new_appointment

  # Crear Cita
  post 'appointment/:id', to: 'appointment#create', as: :create_appointment

  # Aceptar Cita
  put 'perfil/:id/:appointment_id', to: 'appointment#accept', as: :accept_appointment
end

app/models/application_record.rb
# Descripcion que dice que hace la funcion
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  validates :local_id, :fecha, presence: true

  belongs_to :match
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :contenido, presence: true
  belongs_to :local
  belongs_to :user
end

app/models/comments.rb
class Comment < ApplicationRecord
end

app/models/commune.rb
class Commune < ApplicationRecord
  has_many :users, dependent: :nullify
  has_many :locals, dependent: :nullify
end

app/models/interest.rb
class Interest < ApplicationRecord
  has_and_belongs_to_many :users
end

app/models/local.rb
class Local < ApplicationRecord
  validates :nombre, :descripcion, presence: true

  has_many_attached :images

  def carousel_photo(input)
    if images[input].variable?
      images[input].variant(resize: '800x480!').processed
    else
      images[input]
    end
  rescue StandardError
    'https://bulma.io/images/placeholders/800x480.png'
  end

  belongs_to :user
  belongs_to :commune
  has_many :menus, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :valuations, dependent: :destroy
end

app/models/match.rb
class Match < ApplicationRecord
  belongs_to :user1, class_name: 'User'
  belongs_to :user2, class_name: 'User'
  has_many :appointments
end

app/models/match_request.rb
class MatchRequest < ApplicationRecord
end

app/models/menu.rb
class Menu < ApplicationRecord
  validates :nombre, :descripcion, :precio, presence: true
  belongs_to :local
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :avatar

  def comment_avatar
    if avatar.variable?
      avatar.variant(resize: '128x128!').processed
    else
      avatar
    end
  rescue StandardError
    # La imagen ha sido eliminada
    'https://bulma.io/images/placeholders/128x128.png'
  end

  def match_avatar
    if avatar.variable?
      avatar.variant(resize: '480x600!').processed
    else
      avatar
    end
  rescue StandardError
    # La imagen ha sido eliminada
    'https://bulma.io/images/placeholders/480x600.png'
  end

  belongs_to :commune
  has_and_belongs_to_many :interests
  has_one :local, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :matches
  has_many :match_requests
  has_many :valuations, dependent: :nullify
end

app/models/valuation.rb
class Valuation < ApplicationRecord
  belongs_to :user
  belongs_to :local
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  # Create
  def new
    if current_user
      @comentario = Comment.new
      @local = Local.find(params[:local_id])
      if current_user.id == @local.user_id
        redirect_to local_path(@local.id), notice: 'No puedes comentar en tu propio local'
      else
        render
      end
    else
      redirect_to root_path, notice: 'Debes iniciar sesión para comentar'
    end
  end

  def create
    comentario_params = params.require(:comment).permit(:contenido)
    comentario_params[:user_id] = current_user.id
    comentario_params[:local_id] = params[:local_id]
    @comentario = Comment.create(comentario_params)
    if @comentario.save
      redirect_to local_path(params[:local_id]), notice: 'El comentario ha sido agregado con éxito'
    else
      redirect_to local_path(params[:local_id]), notice: 'Ocurrió un error al crear el Comentario'
    end
  end

  # Read
  def index
    @comentarios = Comment.all
    render :layout => 'admin'
  end

  def show
    if user_signed_in? and current_user.id == params[:user_id].to_i
      @user = User.find(params[:user_id])
      @comentarios = Comment.where("user_id = #{@user.id}")
    else
      redirect_to root_path, notice: "No puedes acceder a esta página"
    end
  end

  def destroy
    @comentario = Comment.find(params[:id])
    @comentario.destroy
    if params[:perfil]
      redirect_to perfil_comentarios_path(current_user.id), notice: "El comentario ha sido eliminado con éxito"
      return
    end
    unless params[:admin]
      redirect_to local_path(params[:local_id]), notice: 'El comentario ha sido eliminado con éxito'
    else
      redirect_to comentarios_path, notice: 'El comentario ha sido eliminado con éxito'
    end
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/communes_helper.rb
module CommunesHelper
end

app/helpers/interests_helper.rb
module InterestsHelper
end

app/helpers/locals_helper.rb
module LocalsHelper
end

app/helpers/match_helper.rb
module MatchHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/miperfil_helper.rb
module MiperfilHelper
end

app/helpers/valuations_helper.rb
module ValuationsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/comments/edit.html.erb
<h1>Comentarios#edit</h1>
<p>Find me in app/views/comentarios/edit.html.erb</p>

app/views/comments/index.html.erb
<section class="section">
<div class="box">
<h1 class="title is-5 has-text-centered">Comentarios</h1>

<table class="table is-fullwidth is-striped">
<thead>
    <tr>
    <th>Usuario</th>
    <th>Local</th>
    <th>Contenido</th>
    <th colspan="3"> Acciones </th>
    </tr>
</thead>

<tbody>
    <% @comentarios.each do |comentario| %>
    <tr>
        <td><%= comentario.user.nombre %></td>
        <td><%= comentario.local.nombre %></td>
        <td><%= comentario.contenido %></td>
        <td><%= link_to 'Eliminar comentario', comentario_path(comentario.id, :admin => true),  method: :delete, class: "button is-danger",
        data: { confirm: "¿Estás seguro?"} %>
        <%= link_to 'Ver usuario', perfil_path(comentario.user_id), class: "button is-link", target: :_blank%>
        <%= link_to 'Ver local', local_path(comentario.local_id), class: "button is-link", target: :_blank%></td>
    </tr>
    <% end %>
</tbody>
</table>

<%= link_to 'Volver al Panel', admin_path, class: "button is-link"%>
</div>
</section>

app/views/comments/new.html.erb
<section class="section">
<div class="columns">
    <div class="column"></div>
    <div class="column is-6">
        <div class="box">
            <h1 class="title has-text-centered"> Nuevo comentario en <%= @local.nombre %></h1>
            <%= form_with(model: @comentario, url: local_comentarios_path(@local.id), method: :post) do |form| %>
                <div class="field">
                    Comentario
                    <%= form.text_area :contenido, class: "textarea is-danger"%>
                </div>

                <div class="actions">
                    <%= form.submit 'Dejar Comentario', class: "button is-primary"%>
                    <%= link_to "Volver", local_path(@local.id), class: "button is-link"%>
                </div>
            <% end %>
        </div>
    </div>
    <div class="column"></div>
</div>
</section>

app/views/comments/show.html.erb
<script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>

<section class="hero is-danger">
  <div class="hero-body">
    <div class="container">
      <h1 class="title has-text-centered"> Mis comentarios </h1>
      <h2 class="subtitle has-text-centered"> En esta sección puedes administrar los comentarios que has dejado en algún local</h2>
    </div>
  </div>
</section>

<div class="tabs is-centered">
  <ul>
    <li><%= link_to "Mis Datos", perfil_path(current_user.id)%></li>
    <li class="is-active"><%= link_to 'Mis Comentarios', perfil_comentarios_path(current_user.id)%></li>
    <li><%= link_to 'Citas y Valoraciones Pendientes', perfil_valuations_path(current_user.id)%></li>
  </ul>
</div>

<section class="section">
  <div class="columns">
    <div class="column"></div>
    <div class="column is-two-thirds">
      <% @comentarios.each do |comentario|%>
        <% local = Local.find(comentario.local_id)%>
        <div class="box">
            <article class="media">
             <div class="media-content">
                <div class="content">
                    <p><small><i><%= comentario.created_at.strftime("%d-%m-%Y")%></i> a las <i><%= comentario.created_at.strftime("%H:%M")%>
                    en <%= link_to local.nombre, local_path(local.id), target: :_blank%> </i></small>
                    <br>
                    <%= comentario.contenido %>
                    </p>
                </div>
                <div class="buttons">
                <% if user_signed_in? and current_user.id == comentario.user_id%>
                <%= link_to 'Eliminar Comentario', local_comentario_path(comentario.local_id, comentario.id, perfil: true), method: :delete, class: "button is-danger"%>
                <% end %>
                </div>
            </div>
            </article>
        </div>
      <% end %>
    </div>
    <div class="column"></div>
  </div>
</section>