config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'

  # Administrador
  get 'admin', to: 'admin#index'

  scope '/admin' do
    get 'usuarios', to: 'perfil#index', as: 'admin_usuarios'
    get 'locales', to: 'admin#ver_locales', as: 'admin_locales'
    delete 'locales/:local_id', to: 'admin#eliminar_local', as: 'admin_delete_local'
    get 'aceptar_locales', to: 'admin#aceptar_locales', as: 'admin_aceptar_locales'
    patch 'aceptar_locales/:local_id', to: 'admin#aceptar_local', as: 'admin_aceptar_local'
    resources :comunas, controller: 'communes'
    resources :gustos, controller: 'interests'
    resources :comentarios, controller: 'comments', only: %i[index destroy]
  end

  # Locales, Menus y Comentarios
  resources :locales, controller: 'locals', as: 'local' do
    resources :menus, only: %i[new create edit update destroy]
    resources :comentarios, controller: 'comments', only: %i[new create destroy]
    resources :valoraciones, controller: 'valuations', only: %i[edit update destroy]
  end
  # Perfil
  # Create
  devise_for :users, controllers: { sessions: 'users/sessions',
                                    registrations: 'users/registrations' }

  # Ver menus
  get 'locales/:local_id/edit/menus', to: 'menus#show', as: :local_menues

  # Imagenes del local
  get 'locales/:local_id/edit/imagenes', to: 'locals#images', as: :local_images
  patch 'locales/:local_id/edit/imagenes', to: 'locals#update_images', as: :local_add_images
  delete 'locales/:local_id/edit/imagenes/:image_id', to: 'locals#delete_images',
                                                      as: :local_delete_images

  # Ver comentarios
  get 'perfil/:user_id/comentarios', to: 'comments#show', as: :perfil_comentarios
  # Ver valoraciones pendientes
  get 'perfil/:user_id/valoraciones', to: 'perfil#valuations', as: :perfil_valuations

  # Read perfil
  get 'perfil/:user_id', to: 'perfil#show', as: :perfil

  # Update perfil
  get 'perfil/:id/edit', to: 'perfil#edit', as: :perfil_edit
  patch 'perfil/:id', to: 'perfil#update'
  put 'perfil/:id', to: 'perfil#update'

  # Update interes
  patch 'perfil_interest/:id', to: 'perfil#update_interest', as: :perfil_edit_interest
  get 'perfil/:id/:idinterest', to: 'perfil#delete_interest', as: :perfil_delete_interest

  # Update Profile Avatar
  patch 'perfil_avatar/:user_id', to: 'perfil#update_avatar', as: :perfil_update_avatar
  delete 'perfil_avatar/:user_id', to: 'perfil#delete_avatar', as: :perfil_delete_avatar

  # Delete perfil
  delete 'perfil/:id', to: 'perfil#destroy'

  # Match
  # Mostrar perfiles
  get 'match/:id', to: 'matches#index', as: :match
  # Mostrar informacion de los matches del usuario
  get 'match/:id/info', to: 'matches#show', as: :match_info

  # Create match
  get 'match/:id/:idsolicitado', to: 'matches#new', as: :match_new
  # Aceptar/Rechazar match_request
  patch 'perfil/:id/:id_matchrequest', to: 'matches#accept_match', as: :perfil_accept_match

  # CITAS
  # Proponer Cita
  get 'appointment/:id', to: 'appointment#new', as: :new_appointment

  # Crear Cita
  post 'appointment/:id', to: 'appointment#create', as: :create_appointment

  # Aceptar Cita
  put 'perfil/:id/:appointment_id', to: 'appointment#accept', as: :accept_appointment
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  validates :local_id, :fecha, presence: true

  belongs_to :match
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :contenido, presence: true
  belongs_to :local
  belongs_to :user
end

app/models/comments.rb
class Comment < ApplicationRecord
end

app/models/commune.rb
class Commune < ApplicationRecord
  has_many :users, dependent: :nullify
  has_many :locals, dependent: :nullify
end

app/models/interest.rb
class Interest < ApplicationRecord
  has_and_belongs_to_many :users
end

app/models/local.rb
class Local < ApplicationRecord
  validates :nombre, :descripcion, presence: true

  has_many_attached :images

  def carousel_photo(input)
    if images[input].variable?
      images[input].variant(resize: '800x480!').processed
    else
      images[input]
    end
  rescue StandardError
    'https://bulma.io/images/placeholders/800x480.png'
  end

  belongs_to :user
  belongs_to :commune
  has_many :menus, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :valuations, dependent: :destroy
end

app/models/match.rb
class Match < ApplicationRecord
  belongs_to :user1, class_name: 'User'
  belongs_to :user2, class_name: 'User'
  has_many :appointments
end

app/models/match_request.rb
class MatchRequest < ApplicationRecord
end

app/models/menu.rb
class Menu < ApplicationRecord
  validates :nombre, :descripcion, :precio, presence: true
  belongs_to :local
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :avatar

  def comment_avatar
    if avatar.variable?
      avatar.variant(resize: '128x128!').processed
    else
      avatar
    end
  rescue StandardError
    # La imagen ha sido eliminada
    'https://bulma.io/images/placeholders/128x128.png'
  end

  def match_avatar
    if avatar.variable?
      avatar.variant(resize: '480x600!').processed
    else
      avatar
    end
  rescue StandardError
    # La imagen ha sido eliminada
    'https://bulma.io/images/placeholders/480x600.png'
  end

  belongs_to :commune
  has_and_belongs_to_many :interests
  has_one :local, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :matches
  has_many :match_requests
  has_many :valuations, dependent: :nullify
end

app/models/valuation.rb
class Valuation < ApplicationRecord
  belongs_to :user
  belongs_to :local
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/communes_helper.rb
module CommunesHelper
end

app/helpers/interests_helper.rb
module InterestsHelper
end

app/helpers/locals_helper.rb
module LocalsHelper
end

app/helpers/match_helper.rb
module MatchHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/miperfil_helper.rb
module MiperfilHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/aceptar_locales.html.erb
<section class="section">
<div class="box">
<h1 class="title is-5 has-text-centered">Aceptar locales</h1>

<table class="table is-fullwidth is-striped">
<thead>
    <tr>
    <th>Nombre</th>
    <th>Descripción</th>
    <th>Dirección</th>
    <th>Comuna</th>
    <th>Teléfono</th>
    <th>Acciones</th>
    </tr>
</thead>

<tbody>
    <% @locales_pendientes.each do |local| %>
    <tr>
        <td><%= local.nombre %></td>
        <td><%= local.descripcion %></td>
        <td><%= local.direccion %></td>
        <td><%= local.commune.nombre%></td>
        <td><%= local.telefono %></td>
        <td><%= link_to 'Aceptar local', admin_aceptar_local_path(local.id), method: :patch, class: "button is-primary"%>
            <%= link_to 'Rechazar local', admin_delete_local_path(local.id, aceptado: "no"), method: :delete, class: "button is-danger",
            data: { confirm: "¿Estás seguro?"}%></td>
    </tr>
    <% end %>
</tbody>
</table>

<%= link_to 'Volver al Panel', admin_path, class: "button is-link"%>
</div>
</section>

app/views/admin/index.html.erb
<section class="section">
	<div class="columns">
		<div class="column"></div>
		<div class="column is-4">
			<h1 class="title has-text-centered">¿Qué deseas administrar?</h1>
			<div class="list is-hoverable">
				<%= link_to "Comunas", comunas_path, class: "list-item has-text-centered"%>
				<%= link_to "Gustos", gustos_path, class: "list-item has-text-centered"%>
				<%= link_to "Locales", admin_locales_path, class: "list-item has-text-centered"%>
				<%= link_to "Usuarios", admin_usuarios_path, class: "list-item has-text-centered"%>
				<%= link_to "Comentarios", comentarios_path, class: "list-item has-text-centered"%>
				<%= link_to "Aceptar locales", admin_aceptar_locales_path, class: "list-item has-text-centered"%>
			</div>
		</div>
		<div class="column"></div>
</section>

app/views/admin/locales.html.erb
<section class="section">
<div class="box">
<h1 class="title is-5 has-text-centered">Locales</h1>

<table class="table is-fullwidth is-striped">
<thead>
    <tr>
    <th>Nombre</th>
    <th>Descripción</th>
    <th>Acciones</th>
    </tr>
</thead>

<tbody>
    <% @locales.each do |local| %>
    <tr>
        <td><%= local.nombre %></td>
        <td><%= local.descripcion %></td>
        <td><%= link_to 'Eliminar local', admin_delete_local_path(local.id, aceptado: "si"),  method: :delete, class: "button is-danger", data: { confirm:
        "¿Estás seguro?"} %>
        <%= link_to 'Ver local', local_path(local.id), class: "button is-primary", target: :_blank%></td>
    </tr>
    <% end %>
</tbody>
</table>

<%= link_to 'Volver al Panel', admin_path, class: "button is-link"%>
</div>
</section>