config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'

  # Administrador
  get 'admin', to: 'admin#index'

  scope '/admin' do
    get 'usuarios', to: 'perfil#index', as: 'admin_usuarios'
    get 'locales', to: 'admin#ver_locales', as: 'admin_locales'
    delete 'locales/:local_id', to: 'admin#eliminar_local', as: 'admin_delete_local'
    get 'aceptar_locales', to: 'admin#aceptar_locales', as: 'admin_aceptar_locales'
    patch 'aceptar_locales/:local_id', to: 'admin#aceptar_local', as: 'admin_aceptar_local'
    resources :comunas, controller: 'communes'
    resources :gustos, controller: 'interests'
    resources :comentarios, controller: 'comments', only: %i[index destroy]
  end

  # Locales, Menus y Comentarios
  resources :locales, controller: 'locals', as: 'local' do
    resources :menus, only: %i[new create edit update destroy]
    resources :comentarios, controller: 'comments', only: %i[new create destroy]
    resources :valoraciones, controller: 'valuations', only: %i[edit update destroy]
  end
  # Perfil
  # Create
  devise_for :users, controllers: { sessions: 'users/sessions',
                                    registrations: 'users/registrations' }

  # Ver menus
  get 'locales/:local_id/edit/menus', to: 'menus#show', as: :local_menues

  # Imagenes del local
  get 'locales/:local_id/edit/imagenes', to: 'locals#images', as: :local_images
  patch 'locales/:local_id/edit/imagenes', to: 'locals#update_images', as: :local_add_images
  delete 'locales/:local_id/edit/imagenes/:image_id', to: 'locals#delete_images',
                                                      as: :local_delete_images

  # Ver comentarios
  get 'perfil/:user_id/comentarios', to: 'comments#show', as: :perfil_comentarios
  # Ver valoraciones pendientes
  get 'perfil/:user_id/valoraciones', to: 'perfil#valuations', as: :perfil_valuations

  # Read perfil
  get 'perfil/:user_id', to: 'perfil#show', as: :perfil

  # Update perfil
  get 'perfil/:id/edit', to: 'perfil#edit', as: :perfil_edit
  patch 'perfil/:id', to: 'perfil#update'
  put 'perfil/:id', to: 'perfil#update'

  # Update interes
  patch 'perfil_interest/:id', to: 'perfil#update_interest', as: :perfil_edit_interest
  get 'perfil/:id/:idinterest', to: 'perfil#delete_interest', as: :perfil_delete_interest

  # Update Profile Avatar
  patch 'perfil_avatar/:user_id', to: 'perfil#update_avatar', as: :perfil_update_avatar
  delete 'perfil_avatar/:user_id', to: 'perfil#delete_avatar', as: :perfil_delete_avatar

  # Delete perfil
  delete 'perfil/:id', to: 'perfil#destroy'

  # Match
  # Mostrar perfiles
  get 'match/:id', to: 'matches#index', as: :match
  # Mostrar informacion de los matches del usuario
  get 'match/:id/info', to: 'matches#show', as: :match_info

  # Create match
  get 'match/:id/:idsolicitado', to: 'matches#new', as: :match_new
  # Aceptar/Rechazar match_request
  patch 'perfil/:id/:id_matchrequest', to: 'matches#accept_match', as: :perfil_accept_match

  # CITAS
  # Proponer Cita
  get 'appointment/:id', to: 'appointment#new', as: :new_appointment

  # Crear Cita
  post 'appointment/:id', to: 'appointment#create', as: :create_appointment

  # Aceptar Cita
  put 'perfil/:id/:appointment_id', to: 'appointment#accept', as: :accept_appointment
end

app/models/match.rb
class Match < ApplicationRecord
  belongs_to :user1, class_name: 'User'
  belongs_to :user2, class_name: 'User'
  has_many :appointments
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  def show
  end

  def index
    unless user_signed_in?
      redirect_to root_path, notice: 'Usted debe iniciar sesión para poder realizar match'
    else
      #@users = User.all.paginate(page: params[:page], per_page: 2)
      @user = User.find(params[:id])
      if params[:genero]
        if params[:genero] != "Todas" and params[:commune_id] != 'Todas'
          @users_previus = User.where("id != ? AND admin = false AND genero = ? AND commune_id = ?", @user.id, params[:genero], params[:commune_id])
        elsif params[:commune_id] != 'Todas'
          @users_previus = User.where("id != ? AND admin = false AND commune_id = ?", @user.id, params[:commune_id])
        elsif params[:genero] != 'Todas'
          @users_previus = User.where("id != ? AND admin = false AND genero = ?", @user.id, params[:genero])
        else
          @users_previus = User.where("id != " + @user.id.to_s + " AND admin = false")
        end
      else
        @users_previus = User.where("id != " + @user.id.to_s + " AND admin = false")
      end
      @matches_listos = Match.all
      @matches_request = MatchRequest.where("solicitante_id = " + @user.id.to_s)
      @users = []
      
      @users_previus.each do |user|
        repetido = false
        @matches_request.each do |match_request|
          if match_request.solicitado_id == user.id
            repetido = true
            break
          end
        end
        @matches_listos.each do |match|
          if match.user1_id == @user.id and match.user2_id == user.id
            repetido = true
            break
          elsif match.user2_id == @user.id and match.user1_id == user.id
            repetido = true
            break
          end
        end
        if not repetido
          @users << user
        end
      end
      @users = @users.shuffle!
      @users = @users.paginate(page: params[:page], per_page: 3)
        
    end
  end

  def show
    @user = User.find(params[:id])
    
    @pending_valuations = current_user.valuations.where("realizada = false")

    @current_date = DateTime.now.to_date

    # #Cada vez que entra a su perfil busca posibles match que se hayan hecho mutuamente por casualidad
    # @match_nuevos = MatchRequest.where('solicitado_id = ?', @user.id)
    # @match_nuevos.each do |m|
    #   @match_coincidentes = MatchRequest.where('solicitado_id = ? and solicitante_id = ?', m.solicitante_id, @user.id)
    #   if @match_coincidentes
    #     @match_coincidentes.each do |m2|
    #       match = Match.new(user1_id: m2.solicitante_id,
    #         user2_id: m2.solicitado_id,
    #         cita_realizada: false)
    #       match.save!
    #       m2.destroy
    #       m.destroy
    #     end
    #   end
    # end
    # Match que le han llegado como solicitud
    @match_nuevos = MatchRequest.where('solicitado_id = ?', @user.id)
    # Match que ya a concretado 
    @match_todos = Match.where('user1_id = ? or user2_id = ?', @user.id, @user.id)
  end

  def new
    @user = User.find(params[:id])
    @user_solicitud = User.find(params[:idsolicitado])
    @match_request = MatchRequest.new(
      solicitante_id: @user.id,
      solicitado_id: @user_solicitud.id
    )
    @match_request.save!
    notificacion = false
    @match_nuevos = MatchRequest.where('solicitado_id = ?', @user.id)
    @match_nuevos.each do |m|
      @match_coincidentes = MatchRequest.where('solicitado_id = ? and solicitante_id = ?', m.solicitante_id, @user.id)
      if @match_coincidentes
        @match_coincidentes.each do |m2|
          match = Match.new(user1_id: m2.solicitante_id,
            user2_id: m2.solicitado_id,
            cita_realizada: false)
          notificacion = true
          match.save!
          m2.destroy
          m.destroy
        end
      end
    end
    # Match que le han llegado como solicitud
    @match_nuevos = MatchRequest.where('solicitado_id = ?', @user.id)
    # Match que ya a concretado 
    @match_todos = Match.where('user1_id = ? or user2_id = ?', @user.id, @user.id)
    if notificacion
      redirect_to match_path(@user.id), notice: "Acabas de hacer MATCH, revisa la seccion de match para más informacion"
    else
      redirect_to match_path(@user.id)
    end
  end

  def accept_match
    if params[:aceptar] == "true"
      @user = User.find(params[:id])
      @match_request = MatchRequest.find(params[:id_matchrequest])
      match = Match.new(user1_id: @match_request.solicitante_id,
                user2_id: @match_request.solicitado_id,
                cita_realizada: false,
                local_id: nil)
      match.save!
      @match_request.destroy
      redirect_to perfil_path(@user.id)
    else
      @user = User.find(params[:id])
      @match_request = MatchRequest.find(params[:id_matchrequest])
      @match_request.destroy
      redirect_to perfil_path(@user.id)
    end
  end
end

app/helpers/match_helper.rb
module MatchHelper
end

app/views/matches/index.html.erb
<style>
.bm--card-equal-height {
   display: flex;
   flex-direction: column;
   height: 100%;
}
.bm--card-equal-height .card-footer {
   margin-top: auto;
}
</style>


<!DOCTYPE html>
<html>
<head>
  <title>MatchMeat</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.8.2/css/bulma.min.css">
  <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
  <style>
    ul#interests li {
      display:inline;
    }
  </style>
</head>
<body>
<section class="hero is-danger">
  <div class="hero-body">
    <div class="container">
      <h1 class="title has-text-centered">Matchs</h1>
      <h2 class="subtitle has-text-centered">En esta sección puedes ver a todos los usuarios y enviar una solicitud de MATCH</h2>
    </div>
  </div>
</section>

<br>
<div class="tabs is-centered">
  <ul>
    <li class="is-active"><a href="<%=match_path(current_user.id)%>">Buscar Suerte</a></li>
    <li><%= link_to 'Tus Matchs', match_info_path(current_user.id)%></li>
    <%# <li class="button" data-toggle="collapse" href="#collapseOne" role="button" aria-expanded="false" aria-controls="collapseExample">
        Filtrar
    </li> %>
  </ul>
</div>

<%= form_tag match_path, :method => 'get' do %>
<div class="field-body">
  &nbsp;&nbsp;&nbsp;
  <div class="field">
    <div class="control">
      Comuna:
      <div class="select is-fullwidth">
        <% comunas = Commune.all.collect {|c| [c.nombre, c.id]} %>
        <% comunas.unshift("Todas") %>
        <%= select_tag(:commune_id, options_for_select(comunas)) %>
      </div>
    </div>
  </div>
  <div class="field">
    <div class="control">
      Genero:
      <div class="select is-fullwidth">
        <%= select_tag(:genero, options_for_select(["Todas", "Masculino", "Femenino", "Otro"])) %>
      </div>
    </div>
  </div>
  <div>
    <br>
    <div><%= submit_tag "Aplicar Filtros", :name => nil, class: "button is-warning is-light" %></div>
  </div>
  &nbsp;&nbsp;&nbsp;
</div>
<% end %>

<section class="section">
<div class="columns">
  <%@users.each do |user|%>
  <div class="column">
    <div class="card bm--card-equal-height">
      <div class="card-image">
        <figure class="image is-4by5">
          <% unless user.avatar.attached? %>
            <img src="https://bulma.io/images/placeholders/480x600.png" alt="Placeholder image">
          <% else %>
            <%= image_tag(user.match_avatar) %>
          <% end %>
        </figure>
      </div>
      <div class="card-content">
        <div class="media">
          <div class="media-content">
            <p class="title is-4"><%= user.nombre %></p>
            <p class="subtitle is-6"><%= user.edad%> años</p>
          </div>
        </div>

        <div class="content">
          <p>
            <strong><%= user.nombre %></strong> <small><%= user.edad %> años</small> 
            <br>
            <strong>Comuna: </strong>
            <%= user.commune.nombre %>
            <br>
            <strong>Descripcion: </strong>
            <%= user.descripcion %> 
            <br>
            <strong>Genero: </strong>
            <%= user.genero%>
          </p>
          <div class="control">
            <div class="tab">
            <div class="tags">
              <strong>Gustos:</strong>
              <ul id="interests">
                <% user.interests.each do |interest|%>
                  <li>
                  <span class="tag is-danger is-light"><%= interest.nombre %><span>
                  </li>
                <% end %>
              </ul>
            </div>
            </div>
          </div>
          <br>
          <div style="width:60px; margin:0 auto;">
          <nav class="level is-mobile">
            <div align="center">
              <a class="level-item" aria-label="like" href="<%=match_new_path(@user.id, user.id)%>">
                <span class="icon is-medium is-centered">
                    <i class="fas fa-heart fas fa-2x" aria-hidden="true"></i>
                </span>
              </a>
            </div>
          </nav>
          </div>
        </div>
      </div>
    </div>
  </div>
  <%end%>
  <% if @users.length % 3 == 1%>
    <div class="column"></div>
    <div class="column"></div>
  <% elsif @users.length % 3 == 2%>
    <div class="column"></div>
  <% end %>
</div>
</section>
<div style="width:200px; margin:0 auto;">
  <%= will_paginate @users, :page_links => false, renderer: BulmaPagination::Rails, class: 'pagination is-rounded', :previous_label => 'Anterior', :next_label => 'Siguiente' %>
</div>
</body>
</html>

app/views/matches/show.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MatchMeat</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.8.2/css/bulma.min.css">
  <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
  <style>
    ul#interests li {
      display:inline;
    }
  </style>
</head>
<body>
<section class="hero is-danger">
  <div class="hero-body">
    <div class="container">
      <h1 class="title has-text-centered">Tus Matchs</h1>
      <h2 class="subtitle has-text-centered">En esta sección puedes ver toda la información de tus matches</h2>
    </div>
  </div>
</section>

<br>
<div class="tabs is-centered">
  <ul>
    <li><a href="<%=match_path(current_user.id)%>">Buscar Suerte</a></li>
    <li class="is-active"><a href="<%=match_info_path(current_user.id)%>">Tus Matchs</a></li>
  </ul>
</div>

<section class="section">
<div class="columns">
  <div class="column">
    <div class="box" style="color: is-danger;">
      <div class="content">
        <h2><center> Mis match </center></h2>
        <table class="table">
          <thead>
            <tr>
              <th> Persona  </th>
              <th> Telefono </th>
              <th> Correo </th>
              <th> Acción </th>
            </tr>
          </thead>
          <tbody>
            <% @match_todos.each do |match|%>
              <% if match.user1_id == @user.id %>
                <% @persona = User.find(match.user2_id) %>
              <% else %>
                <% @persona = User.find(match.user1_id) %>
              <% end %>
            <tr>
              <% unless match.cita_realizada %>
              <td> <%= link_to @persona.nombre, perfil_path(@persona.id), target: :_blank%> </td>
              <td> <%= @persona.telefono %></td>
              <td> <%= @persona.email %> </td>
              <td> <%= link_to 'Proponer cita', new_appointment_path(@user.id, match_id: match.id, cita: @persona.nombre), method: :get, class: "button is-primary"%> </td>
              <% end %>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
  <div class='column'>
    <div class="box" style="color: is-danger;">
      <div class="content">
        <h2><center> Agenda de citas </center></h2>
        <table class="table">
          <thead>
            <tr>
              <th> Persona  </th>
              <th> Lugar </th>
              <th> Fecha </th>
              <th> Acción </th>
            </tr>
          </thead>
          <tbody>
            <% @match_todos.each do |match|%>
              <% @appointments = match.appointments.where('solicitante_id != ?', @user.id) %>
              <% if match.user1_id == @user.id %>
                <% @persona = User.find(match.user2_id) %>
              <% else %>
                <% @persona = User.find(match.user1_id) %>
              <% end %>
              <% @appointments.each do |appointment|%>
                <% @lugar = Local.find(appointment.local_id) %>
              <tr>
                <% unless match.cita_realizada %>
                <td> <%= link_to @persona.nombre, perfil_path(@persona.id), target: :_blank %> </td>
                <td> <%= link_to @lugar.nombre, local_path(@lugar.id), target: :_blank %></td>
                <td> <%= appointment.fecha.strftime("%d-%m-%Y") %> </td>
                <td> <%= link_to 'Aceptar', accept_appointment_path(@user.id, appointment.id, accept: true), method: :put, class: "button is-success"%> /
                  <%= link_to 'Rechazar', accept_appointment_path(@user.id, appointment.id, accept: false), method: :put , class: "button is-danger"%></td>
                <% end %>
              </tr>
              <% end %>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
</section>